version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Copy files to server
          command: scp -r -o StrictHostKeyChecking=no * ssh_user@server.com:/var/www/html  #Using key. Put in the key in CircieCI
